Fix: error of window closing when exception occur
LUXROBO/modi-firmware-updater pull request #7
Opened 2021-05-21 06:47 UTC by yjm07

###작업 개요
1 메인 스레드에서 예외가 발생해 정지 상태에서 버튼을 다시 누르면 창이 꺼지는 현상.
2 메인 스레드 안의 스레드에서 업데이트가 진행 중 예외가 발생 시 창이 바로 꺼지는 현상.
위 두가지 에러를 해결하기 위해 예외 발생 시 팝업창을 띄워주도록 작업 진행.

###Jira
해당 사항 없음

###작업 분류
 []버그 수정
 [x]신규 기능
 []프로젝트 구조 변경

###작업 상세 내용
1. sys.excepthook, threading.excepthook를 재정의해 예외 발생 상황의 event를 catch해 팝업을 띄워줌.
2. 팝업 창에 Exit, Report error, Show details 버튼 생성: 각각 창 닫기, 에러 로그 메일 전송, 에러 내용 확인 기능.
  (TODO: Report error 에러 로그 메일 전송)
3. ESP json 통신 시 패킷들이 간섭되어 delimeter 에러가 발생하는 것을 방지하기 위해 sleep(0.1) 추가.
4. Progress bar의 소숫점 1자리로 변경, version info 뒤의 개행(\n) 삭제 등의 사소한 변경.

###생각해볼 문제
1. 예외 상황을 excepthook으로 catch해주고 있는데, 이를 더 개선하는 방법.
2. Report error버튼을 눌렀을 때 이때까지 저장된 로그를 메일로 전송하는 방법.

2021-05-25 15:23 UTC, jha929 commented on modi_firmware_updater/core/esp32_updater.py
> +            time.sleep(0.1)
타이밍때문에 delimiter 에러가 난걸 잘 캐치하셨습니다.

2021-05-25 15:27 UTC, jha929 commented on modi_firmware_updater/core/esp32_updater.py
> +               f"{100 * current / total:3.1f}%"
ESP 펌웨어 버전 업데이트는 시간이 많이 걸려서 일부러 소수점 두번째자리까지 표현하였는데 첫째자리로 바꿔주신 이유가 있을까요?

2021-05-25 15:29 UTC, jha929 commented on modi_firmware_updater/core/stm32_updater.py
> +                version_info = line.decode('utf-8').lstrip('v').rstrip('\n')
version_info에서 new line character를 없애주시는 이유가 있나요? 원래는 이거 없이 잘 동작한 것 같아서요.

2021-05-25 15:31 UTC, jha929 commented on modi_firmware_updater/gui_firmware_updater.py
>  from PyQt5 import QtWidgets, QtCore, QtGui
`import QtWidgets` 이렇게 다 임포트 하는것보다 minimal 하게 임포트 해주시면 좋을 것 같아요.

예를 들어 `from PyQt5.QtWidgets import QMessageBox` 이런식으로요!

2021-05-25 15:36 UTC, jha929 commented on modi_firmware_updater/core/esp32_updater.py
>          return f"Firmware Upload: [{'=' * curr_bar}>{'.' * rest_bar}] " \
가능하다면 backslash `\` 보다는 parentheses `()`로 line continuation을 진행하시면 좋을 것 같아요.

best practice for line continuation 은 의견이 분분한 토픽이지만 저희팀은 parentheses를 권장합니다!

2021-05-25 15:37 UTC, jha929 commented on modi_firmware_updater/gui_firmware_updater.py
> +    def _thread_signal_hook(self):
이 함수만 protected로 설정하신 이유가 있을까요? 없다면 다른 함수들처럼 private으로 바꾸는건 어떨까요?

2021-05-25 15:41 UTC, jha929 commented on modi_firmware_updater/gui_firmware_updater.py
> +        self.setMinimumHeight(100)
이 하드코딩된 숫자들을 설정변수로 저장해서 관리하면 좋을 것 같아요.

2021-05-25 15:42 UTC, jha929 commented on modi_firmware_updater/gui_firmware_updater.py
> +        if textEdit is not None:
파이썬에서 `is not None`도 좋지만 `if textEdit`으로도 인스턴스 체크가 가능하니 이렇게 변경해도 좋을 것 같아요.

2021-05-25 15:43 UTC, jha929 commented on modi_firmware_updater/gui_firmware_updater.py
> +        if textEdit is not None:
추가적으로, `if testEdit`를 쓴 후 코드의 깊이를 줄이고 싶다면, 

```
if not textEdit:
    return result
...
```
이런식으로도 코드를 리팩토링 할 수 있을 것 같아요.

2021-05-25 15:44 UTC, jha929 requested changes
주신 PR에 대해서 리뷰 완료하였습니다.

2021-05-26 03:25 UTC, yjm07 commented on modi_firmware_updater/core/esp32_updater.py
> +               f"{100 * current / total:3.1f}%"
소수점 첫째자리까지 표현해도 진행률이 충분히 빠르게 올라가는 것 같아 불필요하다 생각했습니다.

2021-05-26 03:26 UTC, yjm07 commented on modi_firmware_updater/core/stm32_updater.py
> +                version_info = line.decode('utf-8').lstrip('v').rstrip('\n')
다음 메시지가 version_info 뒤에 같은 행에서 나타났습니다.

2021-06-09 07:32 UTC, yjm07 commented on modi_firmware_updater/gui_firmware_updater.py
> +    def _thread_signal_hook(self):
esp32_firmware_updater 클래스로 저 메소드를 넘겨주는 경우가 있어 private 대신 protected로 했습니다.

2021-06-09 07:34 UTC, jha929 reviewed
전체적으로 제가 수정 부탁드린 부분 잘 해주셨습니다. 리뷰 마치겠습니다.

2021-06-09 07:34 UTC, jha929 commented on modi_firmware_updater/gui_firmware_updater.py
> +        pass
`raise NotImplementedError`로 구현되지 않은 함수들 핸들링이 있다면 더 좋을 것 같아요.

2021-06-09 07:34 UTC, jha929 submitted a review, later dismissed

2021-06-09 08:25 UTC, jha929 approved these changes

2021-06-09 08:26 UTC, merged